### PR TITLE
Fixed last two weeks playtime

### PR DESCRIPTION
**Pull request by SilentException**
Last two weeks playtime on home screen was showing only last day from the statistics. This fixes it.

### CODE REVIEW

**Comment by ynhhoJ** [comment]
In this case there is no need for `else`. You can just add a return:

```js
if (map.has(game.game.id)) {
  map.set(game.game.id, map.get(game.game.id)! + game.time)

  return
}

map.set(game.game.id, game.time)

```

**Comment by SilentException** [comment]
> @SilentException , in this case there is no need for `else`. You can just add a return:
> 
> ```js
> if (map.has(game.game.id)) {
>   map.set(game.game.id, map.get(game.game.id)! + game.time)
> 
>   return
> }
> 
> map.set(game.game.id, game.time)
> ```

Of course, you are correct...it is just that the logic is more readable with else (at least to me) :)

**Comment by SilentException** [comment]
Just adding the build, zip file for manual installation. The build is the same as the one in issue #60...
https://github.com/ma3a/SDH-PlayTime/issues/60#issuecomment-2206098908
...with fix from this PR added.

[SDH-PlayTime-1.0.2-rs1.zip](https://github.com/user-attachments/files/17002442/SDH-PlayTime-1.0.2-rs1.zip)

Use this at your own risk. I assume no responsibility for any issues and do not ask for support from plugin author or Decky Loader team.

**Review by dshk0718 — APPROVED** [review]
Tested that this build of PlayTime plugin works flawlessly.

**Pull request merged**
